HRSensor.Web/Controllers/SurveyManagementController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using System.Web.UI.WebControls;
using static HRSensor.Common.Enums;
using HRSensor.Models;
using HRSensor.Common;
using HRSensor.Repositories.Interfaces;

namespace HRSensor.Web.Controllers
{
    [Authorize(Roles = Constants.ARCHITECT_ROLE + ", " + Constants.HRMONITOR_ROLE)]
    public class SurveyManagementController : BaseController
    {
        private ApplicationDbContext db = new ApplicationDbContext();
        private readonly IUserRepo _userRepo;

        public SurveyManagementController(IUserRepo userRepo) : base(userRepo)
        {
            _userRepo = userRepo;
        }
        // GET: surveys
        public ActionResult Index(string txtDateCreatedFrom, string txtDateCreatedTo, int? cmbUser)
        {

            //List<User> objUslist = (from data in db.User.OrderBy(x => x.FullName).Where(x => x.IsActive == true)
            //                                select data).ToList();
            var loguser = GetUserByAspNetUserId();
            List<User> objUslist = _userRepo.GetAuthors(loguser.OrganizationId);
            User objUs = new User();
            objUs.FullName = "-- Select User --";
            objUs.UserId = 0;
            objUslist.Insert(0, objUs);
            SelectList objUsdata = new SelectList(objUslist, "UserId", "FullName", 0);
            ViewBag.Users = objUsdata;

            var surveys = db.Surveys.Where(c => c.IsActive == true);

            if (!String.IsNullOrEmpty(txtDateCreatedFrom))
            {
                DateTime dtFrom = Convert.ToDateTime(txtDateCreatedFrom);
                surveys = surveys.Where(c => c.CreationDate >= dtFrom);
            }
            if (!String.IsNullOrEmpty(txtDateCreatedTo))
            {
                DateTime dtTo = Convert.ToDateTime(txtDateCreatedTo);
                surveys = surveys.Where(c => c.CreationDate <= dtTo);
            }
            if (cmbUser != 0 && cmbUser != null)
            {
                surveys = surveys.Where(c => c.UserId == cmbUser);
            }

            ModelState.Clear();
            return View(surveys.ToList());
        }

        // GET: surveys/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }
            
            return View(survey);
        }

        //GET: surveys/Create
        public ActionResult Create()
        {
            ViewBag.BusinessUnits = new SelectList(db.BusinessUnits.OrderBy(x => x.BusinessUnitName).Where(x => x.IsActive == true), "BusinessUnitId", "BusinessUnitName");
            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle");
            ViewBag.Departments = new SelectList(db.Departments.OrderBy(x => x.DepartmentName).Where(x => x.IsActive == true), "DepartmentId", "DepartmentName");
            ViewBag.Organizations = new SelectList(db.Organizations.OrderBy(x => x.OrganizationName).Where(x => x.IsActive == true), "OrganizationId", "OrganizationName");
            if (HttpContext.Request.IsAjaxRequest())
                return Json(ViewBag, JsonRequestBehavior.AllowGet);
            return View();
        }

        //POST: surveys/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "SurveyId, SurveyTitle, SurveyCode, OrganizationId, BusinessUnitId, QuestionnaireId, DepartmentId, GeoLocationId, StartDate, EndDate, Status, UserId, CreationDate, CPRS, TimeNeeded, HasHint, WithReview, MandatoryAnswersToAllQuestions, NoOfQuestionsPerPage, WithResultPage, CalculateDistinctWeighting, IsActive")] Survey survey)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (survey.OrganizationId != 0)
                    {
                        var orName = db.Organizations.Find(survey.OrganizationId);
                        survey.Organization = orName;
                    }

                    if (survey.BusinessUnitId != 0 && survey.BusinessUnitId != null)
                    {
                        var buName = db.BusinessUnits.Find(survey.BusinessUnitId);
                        survey.BusinessUnit = buName;
                    }

                    if (survey.DepartmentId != 0 && survey.DepartmentId != null)
                    {
                        var dName = db.Departments.Find(survey.DepartmentId);
                        survey.Department = dName;
                    }

                    if (survey.GeoLocationId != 0 && survey.GeoLocationId != null)
                    {
                        var glName = db.GeoLocations.Find(survey.GeoLocationId);
                        survey.GeoLocation = glName;
                    }

                    var user = GetUserByAspNetUserId();
                    //survey.Author = user;
                    survey.UserId = user.UserId;
                    
                    var qnName = db.Questionnaires.Find(survey.QuestionnaireId);
                    survey.Questionnaire = qnName;
                    survey.CreationDate = DateTime.Now;
                    survey.IsActive = true;
                    survey.Status = SurveyStatus.Outstanding;
                    
                    db.Surveys.Add(survey);

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            catch (Exception exception)
            {
                var ex = exception.Message;
            }

            ViewBag.BusinessUnits = new SelectList(db.BusinessUnits.OrderBy(x => x.BusinessUnitName).Where(x => x.IsActive == true), "BusinessUnitId", "BusinessUnitName", survey.BusinessUnitId);
            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle", survey.QuestionnaireId);
            ViewBag.Departments = new SelectList(db.Departments.OrderBy(x => x.DepartmentName).Where(x => x.IsActive == true), "DepartmentId", "DepartmentName", survey.DepartmentId);
            ViewBag.Organizations = new SelectList(db.Organizations.OrderBy(x => x.OrganizationName).Where(x => x.IsActive == true), "OrganizationId", "OrganizationName", survey.OrganizationId);

            return View(survey);
        }


        // GET: surveys/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Survey survey = db.Surveys.Find(id);
            if (survey == null)
            {
                return HttpNotFound();
            }

            ViewBag.BusinessUnits = new SelectList(db.BusinessUnits.OrderBy(x => x.BusinessUnitName).Where(x => x.IsActive == true), "BusinessUnitId", "BusinessUnitName", survey.BusinessUnitId);
            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle", survey.QuestionnaireId);
            ViewBag.Departments = new SelectList(db.Departments.OrderBy(x => x.DepartmentName).Where(x => x.IsActive == true), "DepartmentId", "DepartmentName", survey.DepartmentId);
            ViewBag.Organizations = new SelectList(db.Organizations.OrderBy(x => x.OrganizationName).Where(x => x.IsActive == true), "OrganizationId", "OrganizationName", survey.OrganizationId);
           
            return View(survey);
        }

        // POST: surveys/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "SurveyId, SurveyTitle, SurveyCode, OrganizationId, BusinessUnitId, QuestionnaireId, DepartmentId, GeoLocationId, StartDate, EndDate, Status, UserId, CreationDate, CPRS, TimeNeeded, HasHint, WithReview, MandatoryAnswersToAllQuestions, NoOfQuestionsPerPage, WithResultPage, CalculateDistinctWeighting, IsActive")] Survey survey)
        {
            if (ModelState.IsValid)
            {
                var surv = db.Surveys.Find(survey.SurveyId);

                surv.QuestionnaireId = survey.QuestionnaireId;
                surv.SurveyTitle = survey.SurveyTitle;
                surv.SurveyCode = survey.SurveyCode;
                surv.OrganizationId = survey.OrganizationId;
                surv.BusinessUnitId = survey.BusinessUnitId;
                surv.DepartmentId = survey.DepartmentId;
                surv.GeoLocationId = survey.GeoLocationId;
                surv.StartDate = survey.StartDate;
                surv.EndDate = survey.EndDate;
                surv.TimeNeeded = survey.TimeNeeded;
                surv.NoOfQuestionsPerPage = survey.NoOfQuestionsPerPage;
                surv.HasHint = survey.HasHint;
                surv.WithReview = survey.WithReview;
                surv.MandatoryAnswersToAllQuestions = survey.MandatoryAnswersToAllQuestions;
                surv.WithResultPage = survey.WithResultPage;
                surv.CalculateDistinctWeighting = survey.CalculateDistinctWeighting;

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.BusinessUnits = new SelectList(db.BusinessUnits.OrderBy(x => x.BusinessUnitName).Where(x => x.IsActive == true), "BusinessUnitId", "BusinessUnitName", survey.BusinessUnitId);

HRSensor.Web/Views/SurveyManagement/Create.cshtml
@model HRSensor.Models.Survey
@{
    Layout = "~/Views/Shared/_LayoutAdminBlack.cshtml";
    ViewBag.Title = "Interview Management";
}
@section styles{
    @Styles.Render("~/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css")
    <link href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
    <!-- Page plugins css -->
    <link href="~/assets/plugins/clockpicker/dist/jquery-clockpicker.min.css" rel="stylesheet">
    <!-- Date picker plugins css -->
    <link href="~/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
}

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Create Interview</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item">Radar</li>
                <li class="breadcrumb-item active">Interviews Management</li>
                <li class="breadcrumb-item active">Create</li>
            </ol>
        </div>
    </div>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.QuestionnaireId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.QuestionnaireId, (SelectList)ViewBag.Questionnaires, "-- Select Questionnaire --", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Questionnaire.QuestionnaireTitle, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SurveyCode, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SurveyCode, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SurveyCode, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.SurveyTitle, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.SurveyTitle, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.SurveyTitle, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.OrganizationId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.OrganizationId, (SelectList)ViewBag.Organizations, "-- Select Organization --", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Organization.OrganizationName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.BusinessUnitId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.BusinessUnitId, (SelectList)ViewBag.BusinessUnits, "-- Select Business Unit --", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.BusinessUnit.BusinessUnitName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.DepartmentId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownListFor(model => model.DepartmentId, (SelectList)ViewBag.Departments, "-- Select Department --", htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.Department.DepartmentName, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.StartDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.EndDate, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.TimeNeeded, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TimeNeeded, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TimeNeeded, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.NoOfQuestionsPerPage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.NoOfQuestionsPerPage, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.NoOfQuestionsPerPage, "", new { @class = "text-danger" })
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.HasHint, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="switch">
                    <label><input type="checkbox" name="HasHint" value="true"><span class="lever"></span></label>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.WithReview, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="switch">
                    <label><input type="checkbox" name="WithReview" value="true"><span class="lever"></span></label>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.MandatoryAnswersToAllQuestions, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="switch">
                    <label><input type="checkbox" name="MandatoryAnswersToAllQuestions" value="true"><span class="lever"></span></label>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.WithResultPage, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="switch">
                    <label><input type="checkbox" name="WithResultPage" value="true"><span class="lever"></span></label>
                </div>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.CalculateDistinctWeighting, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="switch">
                    <label><input type="checkbox" name="CalculateDistinctWeighting" value="true"><span class="lever"></span></label>
                </div>
            </div>
            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-success" />
                    @Html.ActionLink("Back to List", "Index", null, new { @class = "btn waves-effect waves-light  btn-danger" })
                </div>
            </div>
        </div>

    }

</div>
<footer class="footer" style="text-align:center"> Copyright <a href="http://pps.gr"> PPS Limited </a> All rights reserved, Powered by <img src="~/assets/images/azure-logo150.png" alt="Azure logo" /></footer>  @*and <a href="http://www.exceed-systems.com"> Exceed-Systems International</a>*@
@section scripts {
    <script src="~/assets/plugins/moment/moment.js"></script>
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script>
        $('#StartDate').bootstrapMaterialDatePicker({ weekStart: 0, time: false });
        $('#EndDate').bootstrapMaterialDatePicker({ weekStart: 0, time: false });
    </script>

}

HRSensor.Web/Views/SurveyManagement/Index.cshtml
@model IEnumerable<HRSensor.Models.Survey>
@{
    /**/

    Layout = "~/Views/Shared/_LayoutAdminBlack.cshtml";
    ViewBag.Title = "Interviews Management";
}
@section styles{
    @Styles.Render("~/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css")
    <link href="~/assets/plugins/bootstrap-material-datetimepicker/css/bootstrap-material-datetimepicker.css" rel="stylesheet">
    <!-- Page plugins css -->
    <link href="~/assets/plugins/clockpicker/dist/jquery-clockpicker.min.css" rel="stylesheet">
    <!-- Date picker plugins css -->
    <link href="~/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.css" rel="stylesheet" type="text/css" />
}

<div class="container-fluid">
    <div class="row page-titles">
        <div class="col-md-5 align-self-center">
            <h3 class="text-themecolor">Interviews Management</h3>
        </div>
        <div class="col-md-7 align-self-center">
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item">Radar</li>
                <li class="breadcrumb-item active">Interviews Management</li>
            </ol>
        </div>
    </div>
    <br />
    <a href="#searchBox" class="btn waves-effect waves-light  btn-info" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="searchBox">
        Search filters
    </a>
    <div id="searchBox" class="collapse">
        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @using (Html.BeginForm("Index", "SurveyManagement", FormMethod.Get))
            {
                <div class="row col-md-12">
                    <div class="control-label col-md-1">
                        @Html.Label("Date Created From")
                    </div>
                    <div class="col-md-3">
                        <div class="input-group">
                            @Html.TextBox("txtDateCreatedFrom", "", new { id = "date", @class = "form-control" })
                            <span class="input-group-addon"><i class="icon-calender"></i></span>
                        </div>
                    </div>
                    <div class="control-label col-md-1">
                        @Html.Label("Date Created To")
                    </div>
                    <div class="col-md-3">
                        <div class="input-group">
                            @Html.TextBox("txtDateCreatedTo", "", new { id = "date2", @class = "form-control" })
                            <span class="input-group-addon"><i class="icon-calender"></i></span>
                        </div>
                    </div>
                    <div class="control-label col-md-1">
                        @Html.Label("Author")
                    </div>
                    <div class="col-md-3">
                        @Html.DropDownList("cmbUser", (SelectList)ViewBag.Users, new { @class = "form-control" })
                    </div>
                </div>

                <p></p>

                <div class="row col-md-12">
                    <div class="col-md-11 col-md-offset-1">
                        <input type="submit" value="Search" class="btn   btn-warning" />
                    </div>
                </div>
            }
        </div>
    </div>
    <hr />
    <p>
        @Html.ActionLink("Create", "Create", null, new { @class = "btn waves-effect waves-light  btn-success" })
    </p>
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="table-responsive m-t-40">
                        <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Code</th>
                                    <th>Title</th>
                                    <th>Start Date</th>
                                    <th>End Date</th>
                                    <th>Author</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {

                                    <tr>
                                        <td>@item.SurveyId</td>
                                        <td>@item.SurveyCode</td>
                                        <td>@item.SurveyTitle</td>
                                        <td>@item.StartDate.Value.ToShortDateString()</td>
                                        <td>@item.EndDate.Value.ToShortDateString()</td>
                                        <td>@item.Author.FullName</td>
                                        <td>
                                            @Html.ActionLink("Edit", "Edit", new { id = item.SurveyId }) |
                                            @Html.ActionLink("Details", "Details", new { id = item.SurveyId }) |
                                            @Html.ActionLink("Delete", "Delete", new { id = item.SurveyId })
                                        </td>
                                    </tr>

                                }
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="footer" style="text-align:center"> Copyright <a href="http://pps.gr"> PPS Limited </a> All rights reserved, Powered by <img src="~/assets/images/azure-logo150.png" alt="Azure logo" /></footer>  @*and <a href="http://www.exceed-systems.com"> Exceed-Systems International</a>*@
@section scripts{
    <script src="../assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
            $(document).ready(function () {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function (settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function (group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function () {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
    <script src="~/assets/plugins/moment/moment.js"></script>
    <script src="~/assets/plugins/bootstrap-material-datetimepicker/js/bootstrap-material-datetimepicker.js"></script>
    <script src="~/assets/plugins/bootstrap-datepicker/bootstrap-datepicker.min.js"></script>
    <script>
        $('#date').bootstrapMaterialDatePicker({ weekStart: 0, time: false });
        $('#date2').bootstrapMaterialDatePicker({ weekStart: 0, time: false });
    </script>
}