HRSensor.Web/Controllers/QuestionsController.cs
using HRSensor.Common;
using HRSensor.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace HRSensor.Web.Controllers
{
    [Authorize(Roles = Constants.ARCHITECT_ROLE + ", " + Constants.HRMONITOR_ROLE)]
    public class QuestionsController : Controller
    {
        private ApplicationDbContext db = new ApplicationDbContext();

        // GET: questions
        public ActionResult Index(int? cmbQuestionnaire, int? cmbQuestionSector)
        {

            List<Questionnaire> objQlist = (from data in db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true)
                                    select data).ToList();
            Questionnaire objQ = new Questionnaire();
            objQ.QuestionnaireTitle = "-- Select Questionnaire --";
            objQ.QuestionnaireId = 0;
            objQlist.Insert(0, objQ);
            SelectList objQdata = new SelectList(objQlist, "QuestionnaireId", "QuestionnaireTitle", 0);
            ViewBag.Questionnaires = objQdata;

            List<QuestionSector> objQslist = (from data in db.QuestionSectors.OrderBy(x => x.QuestionSectorName).Where(x => x.IsActive == true)
                                            select data).ToList();
            QuestionSector objQs = new QuestionSector();
            objQs.QuestionSectorName = "-- Select Question Sector --";
            objQs.QuestionSectorId = 0;
            objQslist.Insert(0, objQs);
            SelectList objQsdata = new SelectList(objQslist, "QuestionSectorId", "QuestionSectorName", 0);
            ViewBag.QuestionSectors = objQsdata;

            var questions = db.Questions.Where(c => c.IsActive == true);

            if (cmbQuestionnaire != 0 && cmbQuestionnaire != null)
            {
                questions = questions.Where(c => c.QuestionnaireId == cmbQuestionnaire);
            }

            if (cmbQuestionSector != 0 && cmbQuestionSector != null)
            {
                questions = questions.Where(c => c.QuestionSectorId == cmbQuestionSector);
            }

            ModelState.Clear();
            return View(questions.ToList());
        }

        // GET: questions/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            return View(question);
        }

        //GET: questions/Create
        public ActionResult Create()
        {
            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle");
            ViewBag.QuestionSectors = new SelectList(db.QuestionSectors.OrderBy(x => x.QuestionSectorName).Where(x => x.IsActive == true), "QuestionSectorId", "QuestionSectorName");
            if (HttpContext.Request.IsAjaxRequest())
                return Json(ViewBag, JsonRequestBehavior.AllowGet);
            return View();
        }

        //POST: questions/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "QuestionId, QuestionTitle, QuestionCode, QuestionnaireId, QuestionSectorId, Lang, Type, DifficultyLevel, Weight, HasFeedback, HasHint, IsActive")] Question question)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (question.QuestionnaireId != 0)
                    {
                        var qName = db.Questionnaires.Find(question.QuestionnaireId);
                        question.Questionnaire = qName;
                    }

                    if (question.QuestionSectorId != 0)
                    {
                        var qsName = db.QuestionSectors.Find(question.QuestionSectorId);
                        question.QuestionSector = qsName;
                    }

                    question.IsActive = true;

                    db.Questions.Add(question);

                    db.SaveChanges();

                    return RedirectToAction("Index");
                }
            }

            catch (Exception exception)
            {
                var ex = exception.Message;
            }

            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle", question.QuestionnaireId);
            ViewBag.QuestionSectors = new SelectList(db.QuestionSectors.OrderBy(x => x.QuestionSectorName).Where(x => x.IsActive == true), "QuestionSectorId", "QuestionSectorName", question.QuestionSectorId);

            return View(question);
        }


        // GET: questions/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle", question.QuestionnaireId);
            ViewBag.QuestionSectors = new SelectList(db.QuestionSectors.OrderBy(x => x.QuestionSectorName).Where(x => x.IsActive == true), "QuestionSectorId", "QuestionSectorName", question.QuestionSectorId);

            return View(question);
        }

        // POST: questions/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "QuestionId, QuestionTitle, QuestionCode, QuestionnaireId, QuestionSectorId, Lang, Type, DifficultyLevel, Weight, HasFeedback, HasHint, IsActive")] Question question)
        {
            if (ModelState.IsValid)
            {
                var quest = db.Questions.Find(question.QuestionId);

                quest.QuestionTitle = question.QuestionTitle;
                quest.QuestionCode = question.QuestionCode;
                quest.QuestionnaireId = question.QuestionnaireId;
                quest.QuestionSectorId = question.QuestionSectorId;
                quest.Lang = question.Lang;
                quest.Type = question.Type;
                quest.DifficultyLevel = question.DifficultyLevel;
                quest.Weight = question.Weight;
                quest.HasFeedback = question.HasFeedback;
                quest.HasHint = question.HasHint;

                db.SaveChanges();
                return RedirectToAction("Index");
            }

            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle", question.QuestionnaireId);
            ViewBag.QuestionSectors = new SelectList(db.QuestionSectors.OrderBy(x => x.QuestionSectorName).Where(x => x.IsActive == true), "QuestionSectorId", "QuestionSectorName", question.QuestionSectorId);

            return View(question);
        }

        // GET: questions/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Question question = db.Questions.Find(id);
            if (question == null)
            {
                return HttpNotFound();
            }

            ViewBag.Questionnaires = new SelectList(db.Questionnaires.OrderBy(x => x.QuestionnaireTitle).Where(x => x.IsActive == true), "QuestionnaireId", "QuestionnaireTitle", question.QuestionnaireId);
            ViewBag.QuestionSectors = new SelectList(db.QuestionSectors.OrderBy(x => x.QuestionSectorName).Where(x => x.IsActive == true), "QuestionSectorId", "QuestionSectorName", question.QuestionSectorId);

            return View(question);
        }

        // POST: questions/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Question question = db.Questions.Find(id);
            question.IsActive = false;
            db.Entry(question).State = EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

HRSensor.Web/Views/Questions/Create.cshtml
@model HRSensor.Models.Question
@{
    ViewBag.Title = "Create";
}
<h2>Create Question</h2>
<div class="container-fluid">
    <div class="row">
        <div class="col-md-6">
            @using (Html.BeginForm("Create", "Questions"))

            {

            }
        </div>
    </div>
</div>
<footer class="footer" style="text-align:center"> Copyright <a href="http://pps.gr"> PPS Limited </a> All rights reserved, Powered by <img src="~/assets/images/azure-logo150.png" alt="Azure logo" /></footer>  @*and <a href="http://www.exceed-systems.com"> Exceed-Systems International</a>*@ 

HRSensor.Web/Views/Questions/Delete.cshtml
@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

HRSensor.Web/Views/Questions/Details.cshtml
@model HRSensor.Models.Question


@{
    Layout = "~/Views/Shared/_LayoutAdminBlack.cshtml";
    ViewBag.Title = "Question Analysis";
}

@*<h2>@ViewBag.Title</h2>*@

<div>
    <br />
    @*<h4>Question Analysis</h4>*@
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Questionnaire.QuestionnaireTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Questionnaire.QuestionnaireTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionSector.QuestionSectorName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuestionSector.QuestionSectorName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionTitle)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuestionTitle)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.QuestionCode)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.QuestionCode)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Lang)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Lang)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Type)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Type)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DifficultyLevel)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DifficultyLevel)
        </dd>

        @*<dt>
                @Html.DisplayNameFor(model => model.Status)
            </dt>*@
        @*@if (Model.Status == HRSensor.Common.Enums.SurveyStatus.COMPLETED)
                {
                    <dd>Completed</dd>
            }
            else
            {
                <dd>Outstanding</dd>
            }*@

        <dt>
            @Html.DisplayNameFor(model => model.Weight)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Weight)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HasFeedback)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HasFeedback)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.HasHint)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.HasHint)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd>
            <div class="switch">
                @if (Model.IsActive)
                {
                    <label><input type="checkbox" checked="checked" onclick="return false"><span class="lever"></span></label>
                }
                else
                {
                    <label><input type="checkbox" disabled="disabled"><span class="lever"></span></label>
                }
            </div>
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>
<footer class="footer" style="text-align:center"> Copyright <a href="http://pps.gr"> PPS Limited </a> All rights reserved, Powered by <img src="~/assets/images/azure-logo150.png" alt="Azure logo" /></footer>  @*and <a href="http://www.exceed-systems.com"> Exceed-Systems International</a>*@

HRSensor.Web/Views/Questions/Edit.cshtml
@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

HRSensor.Web/Views/Questions/Index.cshtml
@model IEnumerable<HRSensor.Models.Question>
@{
    Layout = "~/Views/Shared/_LayoutAdminBlack.cshtml";
    ViewBag.Title = "Question Management";
}
<h2>@ViewBag.Title</h2>

<br />
<a href="#searchBox" data-toggle="collapse" role="button" aria-expanded="false" aria-controls="searchBox">
    Search filters
</a>
<div id="searchBox" class="collapse">
    <div class="form-horizontal">
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @using (Html.BeginForm("Index", "Questions", FormMethod.Get))
        {
            <div class="row col-md-12">
                <div class="control-label col-md-1">
                    @Html.Label("Questionnaire")
                </div>
                <div class="col-md-3">
                    @Html.DropDownList("cmbQuestionnaire", (SelectList)ViewBag.Questionnaires, new { @class = "form-control" })
                </div>
                <div class="control-label col-md-1">
                    @Html.Label("Question Sector")
                </div>
                <div class="col-md-3">
                    @Html.DropDownList("cmbQuestionSector", (SelectList)ViewBag.QuestionSectors, new { @class = "form-control" })
                </div>
                <div class="col-md-4">
                    <input type="submit" value="Search" class="btn btn-default" />
                </div>
            </div>


        }
    </div>
</div>
<hr />
<p>
    @Html.ActionLink("Create", "Create")
</p>

<div class="row">
    <div class="col-12">
        <div class="card">
            <div class="card-body">
                <h4 class="card-title">Data Export</h4>
                <h6 class="card-subtitle">Export data to Copy, CSV, Excel, PDF & Print</h6>
                <div class="table-responsive m-t-40">
                    <table id="example23" class="display nowrap table table-hover table-striped table-bordered" cellspacing="0" width="100%">
                        <thead>
                            <tr>
                                <th>Id</th>
                                <th>Code</th>
                                <th>Title</th>
                                <th>Questionnaire</th>
                                <th>Question Sector</th>
                                <th>Actions</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {

                                <tr>
                                    <td>@item.QuestionId</td>
                                    <td>@item.QuestionCode</td>
                                    <td>@item.QuestionTitle</td>
                                    <td>@item.Questionnaire.QuestionnaireTitle</td>
                                    <td>@item.QuestionSector.QuestionSectorName</td>
                                    <td>
                                        @Html.ActionLink("Edit", "Edit", new { id = item.QuestionId }) |
                                        @Html.ActionLink("Details", "Details", new { id = item.QuestionId }) |
                                        @Html.ActionLink("Delete", "Delete", new { id = item.QuestionId })
                                    </td>
                                </tr>

                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
<footer class="footer" style="text-align:center"> Copyright <a href="http://pps.gr"> PPS Limited </a> All rights reserved, Powered by <img src="~/assets/images/azure-logo150.png" alt="Azure logo" /></footer>  @*and <a href="http://www.exceed-systems.com"> Exceed-Systems International</a>*@
@section scripts{
    <script src="../assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <!-- start - This is for export functionality only -->
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/dataTables.buttons.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.flash.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jszip/2.5.0/jszip.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/pdfmake.min.js"></script>
    <script src="https://cdn.rawgit.com/bpampuch/pdfmake/0.1.18/build/vfs_fonts.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.html5.min.js"></script>
    <script src="https://cdn.datatables.net/buttons/1.2.2/js/buttons.print.min.js"></script>
    <script>
        $(document).ready(function () {
            $('#myTable').DataTable();
            $(document).ready(function () {
                var table = $('#example').DataTable({
                    "columnDefs": [{
                        "visible": false,
                        "targets": 2
                    }],
                    "order": [
                        [2, 'asc']
                    ],
                    "displayLength": 25,
                    "drawCallback": function (settings) {
                        var api = this.api();
                        var rows = api.rows({
                            page: 'current'
                        }).nodes();
                        var last = null;
                        api.column(2, {
                            page: 'current'
                        }).data().each(function (group, i) {
                            if (last !== group) {
                                $(rows).eq(i).before('<tr class="group"><td colspan="5">' + group + '</td></tr>');
                                last = group;
                            }
                        });
                    }
                });
                // Order by the grouping
                $('#example tbody').on('click', 'tr.group', function () {
                    var currentOrder = table.order()[0];
                    if (currentOrder[0] === 2 && currentOrder[1] === 'asc') {
                        table.order([2, 'desc']).draw();
                    } else {
                        table.order([2, 'asc']).draw();
                    }
                });
            });
        });
        $('#example23').DataTable({
            dom: 'Bfrtip',
            buttons: [
                'copy', 'csv', 'excel', 'pdf', 'print'
            ]
        });
    </script>
}